// Copyright 2017-2021 @axia-js/app-explorer authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @axia-js/dev, do not edit

export const packageInfo = { name: '@axia-js/app-explorer', version: '0.1.0' };
